// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ePatientApi.DataAccess;

#nullable disable

namespace ePatientApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123104257_AddPharmacyAvailability")]
    partial class AddPharmacyAvailability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ePatientApi.Models.AppointmentData", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("appointment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentId"));

                    b.Property<int?>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<string>("DoctorName")
                        .HasColumnType("text")
                        .HasColumnName("doctor_name");

                    b.Property<string>("GoogleEventId")
                        .HasColumnType("text")
                        .HasColumnName("google_event_id");

                    b.Property<string>("PatientBirthNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patient_birth_number");

                    b.Property<DateTime>("ReservationDay")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reservation_day");

                    b.Property<string>("ReservationTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reservation_time");

                    b.HasKey("AppointmentId");

                    b.HasIndex("PatientBirthNumber");

                    b.HasIndex("ReservationDay", "ReservationTime")
                        .IsUnique()
                        .HasDatabaseName("ux_appointments_reservation_day_time");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("ePatientApi.Models.AppointmentSnapshot", b =>
                {
                    b.Property<int>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("snapshot_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SnapshotId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer")
                        .HasColumnName("appointment_id");

                    b.Property<string>("BirthNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("birth_number");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("Insurance")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("insurance");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.HasKey("SnapshotId");

                    b.ToTable("appointmentsdetails", (string)null);
                });

            modelBuilder.Entity("ePatientApi.Models.AvailabilityCheck", b =>
                {
                    b.Property<int>("AvailabilityCheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AvailabilityCheckId"));

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("integer")
                        .HasColumnName("pharmacy_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("ScraperVersion")
                        .HasColumnType("text")
                        .HasColumnName("scraper_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("AvailabilityCheckId");

                    b.HasIndex("PharmacyId");

                    b.HasIndex("ProductId");

                    b.ToTable("availability_checks", (string)null);
                });

            modelBuilder.Entity("ePatientApi.Models.DoctorEmail", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doctor_email");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("text")
                        .HasColumnName("hashedpassword");

                    b.Property<string>("RegistrationCode")
                        .HasColumnType("text")
                        .HasColumnName("registration_code");

                    b.Property<bool>("State")
                        .HasColumnType("boolean")
                        .HasColumnName("state");

                    b.HasKey("DoctorId");

                    b.ToTable("doctoremail");
                });

            modelBuilder.Entity("ePatientApi.Models.ForgotPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientBirthNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PatientBirthNumber");

                    b.ToTable("ForgotPassword");
                });

            modelBuilder.Entity("ePatientApi.Models.HealthCardEntity", b =>
                {
                    b.Property<int>("HealthCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("healthcard_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HealthCardId"));

                    b.Property<string>("AdvanceDirectives")
                        .HasColumnType("text")
                        .HasColumnName("advance_directives");

                    b.Property<string>("BloodType")
                        .HasColumnType("text")
                        .HasColumnName("blood_type");

                    b.Property<string>("ConsentPreferences")
                        .HasColumnType("text")
                        .HasColumnName("consent_preferences");

                    b.Property<string>("ContactAddress")
                        .HasColumnType("text")
                        .HasColumnName("contact_address");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<string>("EmergencyName")
                        .HasColumnType("text")
                        .HasColumnName("emergency_name");

                    b.Property<string>("EmergencyPhone")
                        .HasColumnType("text")
                        .HasColumnName("emergency_phone");

                    b.Property<string>("IdentityCity")
                        .HasColumnType("text")
                        .HasColumnName("identity_city");

                    b.Property<string>("IdentityCountry")
                        .HasColumnType("text")
                        .HasColumnName("identity_country");

                    b.Property<string>("IdentityDateOfBirth")
                        .HasColumnType("text")
                        .HasColumnName("identity_date_of_birth");

                    b.Property<string>("IdentityFirstName")
                        .HasColumnType("text")
                        .HasColumnName("identity_first_name");

                    b.Property<string>("IdentityLastName")
                        .HasColumnType("text")
                        .HasColumnName("identity_last_name");

                    b.Property<string>("Labs")
                        .HasColumnType("text")
                        .HasColumnName("labs");

                    b.Property<string>("PatientBirthNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patient_birth_number");

                    b.Property<int?>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<string>("Surgeries")
                        .HasColumnType("text")
                        .HasColumnName("surgeries");

                    b.HasKey("HealthCardId");

                    b.HasIndex("PatientId");

                    b.ToTable("healthcards", (string)null);
                });

            modelBuilder.Entity("ePatientApi.Models.HealthCardVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("text")
                        .HasColumnName("change_summary");

                    b.Property<string>("DataSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data_snapshot");

                    b.Property<int>("HealthCardId")
                        .HasColumnType("integer")
                        .HasColumnName("healthcard_id");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.ToTable("healthcard_versions", (string)null);
                });

            modelBuilder.Entity("ePatientApi.Models.LoggedDoctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DoctorCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doctorcode");

                    b.Property<string>("DoctorFirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doctorfirstname");

                    b.Property<string>("DoctorLastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doctorlastname");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashedpassword");

                    b.HasKey("Id");

                    b.ToTable("loggeddoctor", (string)null);
                });

            modelBuilder.Entity("ePatientApi.Models.LoggedUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LastName");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.ToTable("loggeduser", (string)null);
                });

            modelBuilder.Entity("ePatientApi.Models.MedicalReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("report_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer")
                        .HasColumnName("appointment_id");

                    b.Property<string>("AttendingDoctor")
                        .HasColumnType("text")
                        .HasColumnName("attendingdoctor");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ExternalExaminations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("externalexaminations");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Medication")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("medication");

                    b.Property<string>("PatientBirthNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patient_birth_number");

                    b.Property<int?>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("ReportId");

                    b.HasIndex("PatientBirthNumber");

                    b.ToTable("medicalreports", (string)null);
                });

            modelBuilder.Entity("ePatientApi.Models.PatientExaminationData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttendingDoctor")
                        .HasColumnType("text")
                        .HasColumnName("attendingdoctor");

                    b.Property<string>("Examination")
                        .HasColumnType("text")
                        .HasColumnName("examination");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<string>("RegisteredPatientBirthNumber")
                        .HasColumnType("text");

                    b.Property<string>("Room")
                        .HasColumnType("text")
                        .HasColumnName("room");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredPatientBirthNumber");

                    b.ToTable("patientexamination");
                });

            modelBuilder.Entity("ePatientApi.Models.Pharmacy", b =>
                {
                    b.Property<int>("PharmacyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PharmacyId"));

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text")
                        .HasColumnName("base_url");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("PharmacyId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("pharmacies", (string)null);
                });

            modelBuilder.Entity("ePatientApi.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ExternalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ProductId");

                    b.HasIndex("ExternalCode");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("ePatientApi.Models.RegisteredDoctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("DoctorCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doctorcode");

                    b.Property<string>("DoctorEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doctor_email");

                    b.Property<string>("DoctorFirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("DoctorHashedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doctor_password");

                    b.Property<string>("DoctorLastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("DoctorPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("VerifiedFirstName")
                        .HasColumnType("text")
                        .HasColumnName("verified_firstname");

                    b.Property<string>("VerifiedFullName")
                        .HasColumnType("text")
                        .HasColumnName("verified_fullname");

                    b.Property<string>("VerifiedLastName")
                        .HasColumnType("text")
                        .HasColumnName("verified_lastname");

                    b.Property<string>("VerifiedSourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("verified_source_url");

                    b.Property<string>("VerifiedSpecialization")
                        .HasColumnType("text")
                        .HasColumnName("verified_specialization");

                    b.HasKey("DoctorId");

                    b.HasIndex("DoctorCode")
                        .IsUnique();

                    b.HasIndex("DoctorEmail")
                        .IsUnique();

                    b.ToTable("registereddoctor", (string)null);
                });

            modelBuilder.Entity("ePatientApi.Models.RegisteredPatient", b =>
                {
                    b.Property<string>("BirthNumber")
                        .HasColumnType("text")
                        .HasColumnName("birthnumber");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("GoogleAccessToken")
                        .HasColumnType("text")
                        .HasColumnName("google_accesstoken");

                    b.Property<string>("GoogleRefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("google_refreshtoken");

                    b.Property<DateTime?>("GoogleTokenExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("google_tokenexpiry");

                    b.Property<int?>("GpDoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("gp_doctor_id");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashedpassword");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Insurance")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("insurance");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phonenumber");

                    b.Property<string>("ResetToken")
                        .HasColumnType("text")
                        .HasColumnName("resettoken");

                    b.Property<DateTime?>("ResetTokenExpiration")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resettokenexpiration");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("BirthNumber");

                    b.HasAlternateKey("Id")
                        .HasName("ux_registeredpatient_id");

                    b.HasIndex("GpDoctorId");

                    b.ToTable("registeredpatient", (string)null);
                });

            modelBuilder.Entity("ePatientApi.Models.WebAuthnCredentials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthenticatorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authenticator_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("credential_id");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key");

                    b.Property<long>("SignatureCounter")
                        .HasColumnType("bigint")
                        .HasColumnName("signature_counter");

                    b.Property<string>("UserHandle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_handle");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_type");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "UserType")
                        .IsUnique();

                    b.ToTable("webauthncredentials", (string)null);
                });

            modelBuilder.Entity("ePatientApi.Models.AppointmentData", b =>
                {
                    b.HasOne("ePatientApi.Models.RegisteredPatient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientBirthNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ePatientApi.Models.AvailabilityCheck", b =>
                {
                    b.HasOne("ePatientApi.Models.Pharmacy", "Pharmacy")
                        .WithMany("AvailabilityChecks")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ePatientApi.Models.Product", "Product")
                        .WithMany("AvailabilityChecks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ePatientApi.Models.ForgotPassword", b =>
                {
                    b.HasOne("ePatientApi.Models.RegisteredPatient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientBirthNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ePatientApi.Models.HealthCardEntity", b =>
                {
                    b.HasOne("ePatientApi.Models.RegisteredPatient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .HasPrincipalKey("Id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ePatientApi.Models.MedicalReport", b =>
                {
                    b.HasOne("ePatientApi.Models.RegisteredPatient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientBirthNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ePatientApi.Models.PatientExaminationData", b =>
                {
                    b.HasOne("ePatientApi.Models.RegisteredPatient", "RegisteredPatient")
                        .WithMany()
                        .HasForeignKey("RegisteredPatientBirthNumber");

                    b.Navigation("RegisteredPatient");
                });

            modelBuilder.Entity("ePatientApi.Models.RegisteredPatient", b =>
                {
                    b.HasOne("ePatientApi.Models.RegisteredDoctor", "GpDoctor")
                        .WithMany()
                        .HasForeignKey("GpDoctorId");

                    b.Navigation("GpDoctor");
                });

            modelBuilder.Entity("ePatientApi.Models.Pharmacy", b =>
                {
                    b.Navigation("AvailabilityChecks");
                });

            modelBuilder.Entity("ePatientApi.Models.Product", b =>
                {
                    b.Navigation("AvailabilityChecks");
                });

            modelBuilder.Entity("ePatientApi.Models.RegisteredPatient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
